### PR TITLE
Fixes for HACS and in main.js

### PR DESCRIPTION
**Pull request by chipriley**
All files to be installed into HA need to be in a `dist` folder according to [HACS dev docs](https://hacs.xyz/docs/publish/plugin).  Either this or include all of the files in the release.  When I installed with HACS, it only installed `main.js` and deleted `styles.js` and `thermostat_card.lib.js`.

Also, there were some syntax issues in `main.js` also causing issues.

### CODE REVIEW

**Comment by fineemb** [comment]
It still doesn't seem to install `styles.js` and `thermostat_card.lib.js` .
I've tried, I still have problems.

**Comment by chipriley** [comment]
Maybe it has to do with it being a release instead of just a commit? Not sure. I know that HACS has been getting updated quite a bit but I’ve never created a plugin deployed through HACS before.

**Comment by chipriley** [comment]
@fineemb Is the latest release version (1.2.7) good to go?  I just don't want to bork my card and I'm running a custom edit of it right now.

**Comment by fineemb** [comment]
Just fixed the HACS issue

**Comment by chipriley** [comment]
When I updated to 1.2.8, HACS only installed `/dist/main.js` and `/dist/main.js.gz`.  No `styles.js` or `thermostat_card.lib.js`.  I had to wget them.  Also had to change the resource reference in `ui-lovelace.yaml` to include the `dist` folder.

**Comment by fineemb** [comment]
need v0.21.5 for HACS

**Pull request merged**
